[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["chmod +x ./node_modules/.bin/react-scripts && npm run build"]

[start]
cmd = "npx serve -s build -l $PORT"
